GET http://localhost:3000/post
Content-Type: application/json;

###
GET http://localhost:3000/post/12
Content-Type: application/json;

###
POST http://localhost:3000/post HTTP/1.1
content-type: application/json

{
    "title": "Title New",
    "content": "Content content content content"
}

###
PUT http://localhost:3000/post/13 HTTP/1.1
content-type: application/json

{
    "title": "Updateeeeeeeeee"
}

###
DELETE http://localhost:3000/post/7 HTTP/1.1
content-type: application/json
