version: '3'

networks:
  om3-network:
    driver: bridge

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_MULTIPLE_DATABASES="starter-api","starter-api-testing"
    volumes:
      - ./.docker:/docker-entrypoint-initdb.d
      - starter_api_data:/data/postgres
    # command: ['docker-entrypoint.sh', 'postgres']
    ports:
      - 5434:5432

volumes:
  starter_api_data: {}
