# build stage
FROM node:latest AS build-stage

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# EXPOSE 3000

# VOLUME 3000

# CMD ["node", "./dist/main.js"]

# production stage
FROM node:latest AS prod-stage

COPY --from=build-stage /app/dist /app
COPY --from=build-stage /app/package.json /app/package.json

WORKDIR /app

RUN npm install --production
RUN npm install -g pm2

EXPOSE 3000

CMD ['pm2-runtime', '/app/main.js']