const NEO4J_CONFIG: string = 'NEO4J_CONFIG';
const NEO4J_CONNECTION: string = 'NEO4J_CONNECTION';
const NEO4J_DRIVER: string = 'NEO4J_DRIVER';

export { NEO4J_CONFIG, NEO4J_CONNECTION, NEO4J_DRIVER };
